use customer_behaviour ; 
select * from customer_purchase limit 20; 
# 1. what is the total revenue generated by male vs.female customer? 
select gender, sum(purchase_amount) as Revenue from customer_purchase
group by gender ;  

# Q2. which customers used a discount still spent more than the average purchase amount ? 
select customer_id, purchase_amount 
from customer_purchase 
where discount_applied = 'yes' and purchase_amount >= (select AVG(purchase_amount) from customer_purchase);

# Q3. which are the top 5 products with highest average review rating? 

SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS "Average Product Rating"
FROM customer_purchase
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

# Q.4 Compare the average purchase amount Amounts between standard and Express shipping ? 
select shipping_type, 
round(avg(purchase_amount),2) as avg_purchaseAmt
from customer_purchase 
where shipping_type in('standard','Express') 
group by shipping_type; 
 
#**Analyst Insight:** Express Shipping generates the highest purchase amount, indicating strong customer preference for 
# faster delivery and an opportunity to focus on express services to drive revenue.

# Q.5 Do subscribed customers spend more? comapare Average spend and total Revenue 
# between subscribers and non-subscribers ? 
select subscription_status, 
count(customer_id) as total_customers, 
Round(avg(purchase_amount),2) as avg_spend, 
Round(sum(purchase_amount),2) as total_Revenue 
from customer_purchase
group by subscription_status 
order by total_Revenue, avg_spend desc; 

# Q6.Which 5 products have the highest percentage of purchase with discount applied ?  
select item_purchased, 
Round(100 * Sum(CASE When discount_applied = 'Yes' Then 1 ELSE 0 END)/count(*),2) as discount_rate 
from customer_purchase 
group by item_purchased 
order by discount_rate Desc 
limit 5; 

# Q7. segment customer into New,Returning and Loyal based on their total number of previous purchases,
# and the count of each segment.. 
with customer_type as( 
select customer_id,Previous_Purchases, 
CASE 
when previous_purchases = 1 THEN 'New'
when previous_purchases BETWEEN 2 and 10 THEN 'Returning' 
ELSE 'Loyal' 
END as customer_segment
from customer_purchase 
) 
select customer_segment, count(*) as "number of customers" 
from customer_type 
group by customer_segment 

#Q8. What are the top 3 most purchased product within each category? 

with item_counts as ( 
select category, 
item_purchased, 
count(customer_id) as total_orders,
Row_Number() over(partition by category order by count(customer_id) desc) as item_rank 
from customer_purchase 
group by category,item_purchased 
) 
select item_rank,category,item_purchased,total_orders 
from item_counts 
where item_rank <= 3 ;
 
# Q.9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe? 
select subscription_status, 
count(customer_id) as repeat_buyers 
from customer_purchase 
where previous_purchases > 5 
group by subscription_status; 

# Q.10 What is the revenue contribution of each age group? 
select age_group, 
sum(purchase_amount) as total_revenue 
from customer_purchase 
group by age_group 
order by total_revenue desc;




